export const es: Record<string, string> = {
  // Sidebar
  Dashboard: "Panel",
  Commissions: "Comisiones",
  Requests: "Solicitudes",
  Clients: "Clientes",
  Tags: "Etiquetas",
  Templates: "Plantillas",
  Finished: "Terminadas",
  Settings: "Ajustes",
  "Commission workspace": "Espacio de comisiones",
  "Hide client names and prices while streaming (Ctrl+Shift+P)": "Oculta nombres de clientes y precios en directo (Ctrl+Shift+P)",
  "Private mode on": "Modo privado activo",
  "Private mode": "Modo privado",
  Shortcuts: "Atajos",
  Search: "Buscar",
  Screens: "Pantallas",

  // Settings
  Preferences: "Preferencias",
  "Appearance, pricing, backups and storage.": "Apariencia, precios, copias y almacenamiento.",
  Appearance: "Apariencia",
  Pricing: "Precios",
  Delivery: "Entrega",
  Backups: "Copias de seguridad",
  "Import payments": "Importar pagos",
  "Export data": "Exportar datos",
  Storage: "Almacenamiento",
  Theme: "Tema",
  "Light, dark, or follow your Windows setting.": "Claro, oscuro o el de tu Windows.",
  Light: "Claro",
  Dark: "Oscuro",
  System: "Sistema",
  Language: "Idioma",
  "The app reloads when you change it.": "La app se recarga al cambiarlo.",
  "Default currency": "Divisa por defecto",
  "New commissions start with this one.": "Las comisiones nuevas empiezan con esta.",
  "Extra character": "Personaje extra",
  "Added to the base price for each character after the first. Commissions you already created keep their price.":
    "Se suma al precio base por cada personaje después del primero. Las comisiones que ya creaste mantienen su precio.",
  "Payment platforms": "Plataformas de pago",
  'Their fees, so "received" fills itself when you log a payment. Use your real rates.':
    'Sus tarifas, para que "recibido" se rellene solo al apuntar un pago. Usa tus tarifas reales.',
  "+ Add platform": "+ Añadir plataforma",
  "Remove platform": "Quitar plataforma",
  "Promised delivery time": "Plazo de entrega prometido",
  "The longest you tell clients it can take. A commission without a deadline counts from the day you accept it.":
    "Lo máximo que dices a tus clientes que puede tardar. Una comisión sin fecha límite cuenta desde el día que la aceptas.",
  days: "días",
  "Delivery reminders": "Avisos de entrega",
  "days before": "días antes",
  "A Windows notification {days} days before and on the day, while ZeeBoard is open.":
    "Una notificación de Windows {days} días antes y el mismo día, mientras ZeeBoard esté abierto.",
  Off: "No",
  On: "Sí",
  "Stalled commissions": "Comisiones paradas",
  "Warns you when a commission has had no new image, correction, payment or stage change for a while.":
    "Te avisa cuando una comisión lleva un tiempo sin imagen nueva, corrección, pago ni cambio de etapa.",
  "Back up your data": "Copia tus datos",
  "Database and images, to any folder. Restoring saves a copy of your current data first.":
    "Base de datos e imágenes, a cualquier carpeta. Al restaurar se guarda antes una copia de tus datos actuales.",
  Export: "Exportar",
  "Exporting…": "Exportando…",
  "Restore…": "Restaurar…",
  "Restoring…": "Restaurando…",
  "Automatic backups": "Copias automáticas",
  "A copy the first time you open ZeeBoard each day. Older copies are removed automatically.":
    "Una copia la primera vez que abres ZeeBoard cada día. Las más antiguas se borran solas.",
  Folder: "Carpeta",
  "Change…": "Cambiar…",
  "Keep the last": "Conservar las últimas",
  copies: "copias",
  "Last backup: {date}": "Última copia: {date}",
  "No automatic backup yet": "Aún no hay copia automática",
  "Back up now": "Copiar ahora",
  "Backing up…": "Copiando…",
  "Choose a folder for automatic backups": "Elige una carpeta para las copias automáticas",
  "Backup saved to: {path}": "Copia guardada en: {path}",
  "Could not back up: {error}": "No se pudo copiar: {error}",
  "Could not create backup. Please try again.": "No se pudo crear la copia. Inténtalo de nuevo.",
  "Could not restore: {error}": "No se pudo restaurar: {error}",
  "PayPal activity (CSV)": "Actividad de PayPal (CSV)",
  "Matches each payment with a client by their email and adds it to their commission, with what you actually received. Payments already imported are skipped.":
    "Cruza cada pago con un cliente por su email y lo añade a su comisión, con lo que realmente recibiste. Los pagos ya importados se saltan.",
  "Last imported payment: {last}. Download from {from}.": "Último pago importado: {last}. Descarga desde {from}.",
  "Nothing imported yet.": "Aún no has importado nada.",
  "Choose CSV": "Elegir CSV",
  "One row per commission: client, type, stage, price and what has been paid.":
    "Una fila por comisión: cliente, tipo, etapa, precio y lo pagado.",
  "One row per payment: date, what the client paid, what you received and the platform fee.":
    "Una fila por pago: fecha, lo que pagó el cliente, lo que recibiste y la tarifa de la plataforma.",
  "Quarterly summary": "Resumen trimestral",
  "Payments grouped by quarter and currency, by the day you received them. Currencies are never added together.":
    "Pagos agrupados por trimestre y divisa, según el día que los recibiste. Las divisas nunca se suman entre sí.",
  Payments: "Pagos",
  "Export CSV": "Exportar CSV",
  "Opens in Excel and Google Sheets (semicolon-separated, decimal comma). Exports always contain the real names and prices, even in private mode.":
    "Se abre en Excel y Google Sheets (separado por punto y coma, coma decimal). Las exportaciones siempre llevan los nombres y precios reales, incluso en modo privado.",
  "Saved to: {path}": "Guardado en: {path}",
  "Could not export: {error}": "No se pudo exportar: {error}",
  "{size} used": "{size} usados",
  "Images {images} ({used} in use · {count} files) · Thumbnails {thumbs} · Database {database}":
    "Imágenes {images} ({used} en uso · {count} archivos) · Miniaturas {thumbs} · Base de datos {database}",
  "Open folder": "Abrir carpeta",
  "Unused images": "Imágenes sin usar",
  "Files that no commission or character uses anymore.": "Archivos que ninguna comisión ni personaje usa ya.",
  "Clean up": "Limpiar",
  "Cleaning up…": "Limpiando…",
  "No unused images found.": "No hay imágenes sin usar.",
  "Deleted {n} unused file · freed {size}.": "Se borró {n} archivo sin usar · liberados {size}.",
  "Deleted {n} unused files · freed {size}.": "Se borraron {n} archivos sin usar · liberados {size}.",
  "Could not back up first, so nothing was deleted: {error}": "No se pudo hacer la copia previa, así que no se borró nada: {error}",
  "Could not clean up images. Please try again.": "No se pudieron limpiar las imágenes. Inténtalo de nuevo.",

  // Settings dialogs
  "Replace your data": "Reemplazar tus datos",
  "Restore this backup?": "¿Restaurar esta copia?",
  "Your current commissions, clients and settings will be replaced by the ones in:\n{folder}\n\nA copy of your current data is saved first (in the app folder, \"before-restore\"), and no images are deleted. The app reloads when it's done.":
    "Tus comisiones, clientes y ajustes actuales se sustituirán por los de:\n{folder}\n\nAntes se guarda una copia de tus datos actuales (en la carpeta de la app, \"before-restore\") y no se borra ninguna imagen. La app se recarga al terminar.",
  "Restore backup": "Restaurar copia",
  Cancel: "Cancelar",
  "Permanent action": "Acción permanente",
  "Clean up unused images": "Limpiar imágenes sin usar",
  "This permanently deletes image files that are no longer linked to any commission or character. A full backup is saved first (in the app folder, 'before-cleanup', keeping the last 2), so you can restore from it if something was needed.":
    "Esto borra para siempre los archivos de imagen que ya no están enlazados a ninguna comisión ni personaje. Antes se guarda una copia completa (en la carpeta de la app, 'before-cleanup', conservando las 2 últimas), para que puedas restaurarla si hacía falta algo.",
  "Delete unused images": "Borrar imágenes sin usar",

  // Dashboard
  Overview: "Resumen",
  "What's on your desk today.": "Lo que hay hoy en tu mesa.",
  "In progress": "En curso",
  commissions: "comisiones",
  "Due within 7 days": "Vencen en 7 días",
  "including overdue": "incluidas las vencidas",
  "Waiting for payment": "Pendiente de cobro",
  "{n} commission": "{n} comisión",
  "{n} commissions": "{n} comisiones",
  "Received this month": "Recibido este mes",
  "{n} payments not entered yet": "{n} pagos sin apuntar lo recibido",
  "{amount} in platform fees": "{amount} en tarifas de plataforma",
  "Needs attention · {n}": "Necesita atención · {n}",
  "In progress · {n}": "En curso · {n}",
  "Nothing on the board. Time for a break.": "Nada en el tablero. Hora de un descanso.",
  "Not started": "Sin empezar",
  "No deadline": "Sin fecha límite",
  "Not paid yet · {n}": "Sin cobrar · {n}",
  "All caught up.": "Todo al día.",
  "Most used tags": "Etiquetas más usadas",
  "No tags in use yet.": "Aún no hay etiquetas en uso.",
  "Booked per month · by commission start date": "Reservado por mes · según el inicio de la comisión",
  "{n} day overdue": "{n} día de retraso",
  "{n} days overdue": "{n} días de retraso",
  "Due today": "Vence hoy",
  "{n} day left": "queda {n} día",
  "{n} days left": "quedan {n} días",
  "{n} day": "{n} día",
  "{n} days": "{n} días",

  // Reminders
  Overdue: "Vencida",
  Today: "Hoy",
  Soon: "Pronto",
  Stalled: "Parada",
  "your promised time": "tu plazo prometido",
  "its deadline": "su fecha límite",
  "{title} is {days} past {limit}": "{title} se pasó {days} de {limit}",
  "{title} reaches {limit} today": "{title} llega hoy a {limit}",
  "{title} reaches {limit} in {days}": "{title} llega a {limit} en {days}",
  "{title} hasn't changed in {days}": "{title} no ha cambiado en {days}",
  "{title} is past the sketch and still unpaid": "{title} ya pasó el boceto y sigue sin pagar",
  "{n} commissions need your attention": "{n} comisiones necesitan tu atención",

  // Commissions
  "Main workspace": "Espacio principal",
  "Organize your drawings by stages, clients, dates and tags.": "Organiza tus dibujos por etapas, clientes, fechas y etiquetas.",
  "+ New commission": "+ Nueva comisión",
  List: "Lista",
  Grid: "Cuadrícula",
  Queue: "En cola",
  "No commissions yet": "Aún no hay comisiones",
  "Create your first commission to start building your workflow.": "Crea tu primera comisión para empezar a montar tu flujo de trabajo.",
  "No matches": "Sin resultados",
  "No commissions match your current search or filters.": "Ninguna comisión coincide con tu búsqueda o filtros.",
  "No client": "Sin cliente",
  "No platform": "Sin plataforma",
  "No price": "Sin precio",
  "No date": "Sin fecha",
  "No base price": "Sin precio base",
  "No notes.": "Sin notas.",
  "No characters.": "Sin personajes.",
  "{n}d": "{n}d",
  "{n}d late": "{n}d de retraso",
  "Days since you accepted it": "Días desde que la aceptaste",
  "Pick a commission": "Elige una comisión",
  "Choose one from the list, or use ↑ ↓ to move between them.": "Elige una de la lista o usa ↑ ↓ para moverte entre ellas.",
  "Each client correction counts as one revision": "Cada corrección del cliente cuenta como una revisión",
  Revisions: "Revisiones",
  extra: "extra",
  "Copy the account to tag when you post": "Copia la cuenta a etiquetar al publicar",
  Tag: "Etiqueta",
  Edit: "Editar",
  "More actions": "Más acciones",
  Duplicate: "Duplicar",
  "Duplicating…": "Duplicando…",
  "Short text for the PayPal invoice": "Texto corto para la factura de PayPal",
  "Copy description": "Copiar descripción",
  Delete: "Borrar",
  "This commission has no template, so it has no stages. Edit it to pick one.": "Esta comisión no tiene plantilla, así que no tiene etapas. Edítala para elegir una.",
  "Open in focus mode": "Abrir en modo enfoque",
  "Previous alt": "Alternativa anterior",
  "Next alt": "Alternativa siguiente",
  "Add an alt": "Añadir una alternativa",
  "Remove this image": "Quitar esta imagen",
  "Optimizing…": "Optimizando…",
  "Drop or Ctrl+V": "Suelta o Ctrl+V",
  "Drop here": "Suelta aquí",
  "+ correction": "+ corrección",
  "{n} correction": "{n} corrección",
  "{n} corrections": "{n} correcciones",
  "Remove correction": "Quitar corrección",
  "What did the client ask to change? Enter to add": "¿Qué pidió cambiar el cliente? Enter para añadir",
  "Back to the previous stage": "Volver a la etapa anterior",
  "‹ Back": "‹ Atrás",
  "✓ Finished": "✓ Terminada",
  "Start {name}": "Empezar {name}",
  "{name} done →": "{name} hecho →",
  "Ctrl+V adds to": "Ctrl+V añade a",
  Notes: "Notas",
  Characters: "Personajes",
  Alt: "Alternativa",
  Alts: "Alternativas",
  Progress: "Progreso",
  Calendar: "Calendario",
  "Next deadline": "Próxima fecha límite",
  Mon: "Lun",
  Tue: "Mar",
  Wed: "Mié",
  Thu: "Jue",
  Fri: "Vie",
  Sat: "Sáb",
  Sun: "Dom",
  "Deadline summary": "Resumen de plazos",
  Deadline: "Fecha límite",
  "Deadline · optional": "Fecha límite · opcional",
  "Commission title": "Título de la comisión",
  Client: "Cliente",
  "Search or type a name": "Busca o escribe un nombre",
  "+ from another client": "+ de otro cliente",
  "· can't change after creating (stages and images depend on it)": "· no se puede cambiar tras crearla (las etapas y las imágenes dependen de ella)",
  Summary: "Resumen",
  Price: "Precio",
  "Calculated from the type and characters; you can change it": "Calculado según el tipo y los personajes; puedes cambiarlo",
  "Background, pose, details to remember…": "Fondo, pose, detalles que recordar…",
  "Saving…": "Guardando…",
  "Create commission": "Crear comisión",
  "Save changes": "Guardar cambios",
  "Delete commission": "Borrar comisión",
  "This action cannot be undone.": "Esta acción no se puede deshacer.",
  "Deleting...": "Borrando...",
  "Commission saved.": "Comisión guardada.",
  "Commission created.": "Comisión creada.",
  "Commission duplicated.": "Comisión duplicada.",
  "Could not duplicate commission.": "No se pudo duplicar la comisión.",
  "Commission deleted.": "Comisión borrada.",
  "Could not delete commission.": "No se pudo borrar la comisión.",
  "Commission error: {error}": "Error en la comisión: {error}",
  "Could not add image: {error}": "No se pudo añadir la imagen: {error}",
  "Tag copied.": "Etiqueta copiada.",
  "Description copied.": "Descripción copiada.",
  "Could not copy it.": "No se pudo copiar.",

  // Filters
  "Search title or client…": "Buscar por título o cliente…",
  "Clear filters": "Quitar filtros",
  "Remove filter": "Quitar filtro",
  Active: "Activas",

  // Payments strip
  "Client paid": "Pagó el cliente",
  "{amount} left": "faltan {amount}",
  "{n} not entered": "{n} sin apuntar",
  "Fees {amount}": "Tarifas {amount}",
  Received: "Recibido",
  Date: "Fecha",
  "You received": "Recibiste",
  "Not yet": "Aún no",
  Later: "Luego",
  "Remove payment": "Quitar pago",
  "Add payment": "Añadir pago",
  "Note: PayPal, deposit…": "Nota: PayPal, adelanto…",
  "Payment error: {error}": "Error de pago: {error}",
  "Enter what the client paid": "Escribe lo que pagó el cliente",

  // Requests
  Intake: "Entrada",
  "People who want a commission: accept them, keep them waiting, or decline.": "Gente que quiere una comisión: acéptala, déjala en espera o recházala.",
  "+ New request": "+ Nueva solicitud",
  "Open for commissions": "Abierto a comisiones",
  Closed: "Cerrado",
  Open: "Abierto",
  "{taken} of {total} slots taken": "{taken} de {total} plazas ocupadas",
  "{n} free": "{n} libres",
  full: "completo",
  "{n} over": "{n} de más",
  slots: "plazas",
  "Every commission that isn't finished takes a slot, including the ones in the queue.": "Cada comisión sin terminar ocupa una plaza, también las que están en cola.",
  "Form responses": "Respuestas del formulario",
  "Not connected: pick the CSV your Google script keeps up to date.": "Sin conectar: elige el CSV que tu script de Google mantiene al día.",
  "Checked {date} · again every 30 minutes": "Comprobado {date} · de nuevo cada 30 minutos",
  "Not checked yet": "Aún sin comprobar",
  "Choose file…": "Elegir archivo…",
  "Check now": "Comprobar ahora",
  "Choose the responses CSV": "Elige el CSV de respuestas",
  "New · {n}": "Nuevas · {n}",
  "Import responses…": "Importar respuestas…",
  "No new requests. Add one with \"+ New request\".": "No hay solicitudes nuevas. Añade una con \"+ Nueva solicitud\".",
  "Waitlist · {n}": "Lista de espera · {n}",
  "You have {n} free slot: time to take someone from the waitlist.": "Tienes {n} plaza libre: toca coger a alguien de la lista de espera.",
  "You have {n} free slots: time to take someone from the waitlist.": "Tienes {n} plazas libres: toca coger a alguien de la lista de espera.",
  "Archive · {n}": "Archivo · {n}",
  Waitlist: "En espera",
  Accept: "Aceptar",
  Decline: "Rechazar",
  Restore: "Restaurar",
  Accepted: "Aceptada",
  Declined: "Rechazada",
  "Remove from the list": "Quitar de la lista",
  "Choose the type…": "Elige el tipo…",
  "Choose the type first": "Elige antes el tipo",
  "Tag when posting:": "Etiquetar al publicar:",
  "{n} character": "{n} personaje",
  "{n} characters": "{n} personajes",
  "New request": "Nueva solicitud",
  Name: "Nombre",
  "@username or email": "@usuario o email",
  "Type of commission": "Tipo de comisión",
  "Number of characters": "Número de personajes",
  "What they asked for: idea, references, links…": "Lo que pidieron: idea, referencias, enlaces…",
  "Add request": "Añadir solicitud",
  "Slots are full": "Plazas completas",
  "Accept anyway": "Aceptar igualmente",
  "Accept {name} anyway?": "¿Aceptar a {name} igualmente?",
  "You have {taken} of {total} slots taken. Accepting adds one more. You can also send them to the waitlist instead.": "Tienes {taken} de {total} plazas ocupadas. Aceptar suma una más. También puedes mandarla a la lista de espera.",
  "{n} new request from the form.": "{n} solicitud nueva del formulario.",
  "{n} new requests from the form.": "{n} solicitudes nuevas del formulario.",
  "Nothing new in the form.": "Nada nuevo en el formulario.",
  "Could not read the responses file: {error}": "No se pudo leer el archivo de respuestas: {error}",
  "No new responses: everything in that file was already imported.": "Sin respuestas nuevas: todo lo de ese archivo ya estaba importado.",
  "Imported {n} new request.": "Se importó {n} solicitud nueva.",
  "Imported {n} new requests.": "Se importaron {n} solicitudes nuevas.",
  "({n} already there)": "({n} ya estaban)",
  "Could not import: {error}": "No se pudo importar: {error}",
  "Could not accept: {error}": "No se pudo aceptar: {error}",
  "Commission created. Edit it to rename it and link the characters.": "Comisión creada. Edítala para renombrarla y vincular los personajes.",
  "A request needs a name and a type.": "Una solicitud necesita un nombre y un tipo.",
  "Could not add the request": "No se pudo añadir la solicitud",
  "Could not set the type": "No se pudo poner el tipo",
  "Could not remove it": "No se pudo quitar",
  "The file is empty": "El archivo está vacío",
  "This doesn't look like your commission form: I can't find the type and contact columns": "Esto no parece tu formulario de comisiones: no encuentro las columnas de tipo y contacto",
  "This doesn't look like a PayPal activity CSV (date, currency, gross, sender email, transaction id)": "Esto no parece un CSV de actividad de PayPal (fecha, divisa, bruto, email del remitente, id de transacción)",

  // PayPal import
  "Choose the PayPal activity CSV": "Elige el CSV de actividad de PayPal",
  "Already imported": "Ya importado",
  "No client with this email": "Ningún cliente con este email",
  "This client has nothing left to pay": "Este cliente no tiene nada pendiente de pagar",
  PayPal: "PayPal",
  "{ready} of {total} payments ready": "{ready} de {total} pagos listos",
  "No incoming payments found in this file.": "No hay pagos recibidos en este archivo.",
  "Importing…": "Importando…",
  "Import {n}": "Importar {n}",

  // Clients
  "Client database": "Base de clientes",
  "Your clients, their characters and their commissions.": "Tus clientes, sus personajes y sus comisiones.",
  "+ New client": "+ Nuevo cliente",
  "Search clients…": "Buscar clientes…",
  "No clients yet": "Aún no hay clientes",
  "No contact": "Sin contacto",
  "Add your first client": "Añade tu primer cliente",
  "Pick a client": "Elige un cliente",
  "Keep their contact, characters and references in one place.": "Guarda su contacto, personajes y referencias en un solo sitio.",
  "Their profile, characters and commissions show up here.": "Aquí aparecen su perfil, personajes y comisiones.",
  "New client": "Nuevo cliente",
  "Edit client": "Editar cliente",
  "Click, drop an image or paste one (Ctrl+V) to change the photo": "Haz clic, suelta una imagen o pega una (Ctrl+V) para cambiar la foto",
  "Fetch photo": "Buscar foto",
  "Fetching…": "Buscando…",
  "Photo updated.": "Foto actualizada.",
  "No public photo found. Drop an image on the avatar to set it yourself.": "No se encontró foto pública. Suelta una imagen sobre el avatar para ponerla tú.",
  "Could not fetch the photo: {error}": "No se pudo buscar la foto: {error}",
  "Could not set the photo: {error}": "No se pudo poner la foto: {error}",
  "{active} active · {done} done": "{active} activas · {done} hechas",
  Spent: "Gastado",
  "{amount} average": "{amount} de media",
  "No commissions yet.": "Aún no hay comisiones.",
  "Open commission": "Abrir comisión",
  Done: "Hecha",
  "Drop to add references": "Suelta para añadir referencias",
  "{refs} refs · {used} commissions": "{refs} refs · {used} comisiones",
  "No references": "Sin referencias",
  "Character name": "Nombre del personaje",
  Add: "Añadir",
  "+ Character": "+ Personaje",
  Save: "Guardar",
  "Notes: species, colours, details to remember…": "Notas: especie, colores, detalles que recordar…",
  "No notes yet.": "Aún no hay notas.",
  "Remove reference": "Quitar referencia",
  "Click, drop images here or paste with Ctrl+V": "Haz clic, suelta imágenes aquí o pega con Ctrl+V",
  "Add · Ctrl+V": "Añadir · Ctrl+V",
  "No image": "Sin imagen",
  "Client name": "Nombre del cliente",
  "@username": "@usuario",
  "Account to tag when posting, e.g. Bluesky @name": "Cuenta a etiquetar al publicar, p. ej. Bluesky @nombre",
  "Email (PayPal), to match their payments": "Email (PayPal), para cruzar sus pagos",
  "Create client": "Crear cliente",
  "Delete character": "Borrar personaje",
  "Its references are deleted too, and it's removed from any commissions. This can't be undone.": "Sus referencias también se borran y se quita de las comisiones. No se puede deshacer.",
  "Delete client": "Borrar cliente",
  "Could not create client.": "No se pudo crear el cliente.",
  "Client deleted.": "Cliente borrado.",
  "Could not delete client.": "No se pudo borrar el cliente.",
  "Could not save client changes.": "No se pudieron guardar los cambios del cliente.",
  "Could not save character.": "No se pudo guardar el personaje.",
  "Character deleted.": "Personaje borrado.",
  "Could not delete character.": "No se pudo borrar el personaje.",
  "Could not add reference image: {error}": "No se pudo añadir la imagen de referencia: {error}",

  // Finished
  Archive: "Archivo",
  "Finished commissions": "Comisiones terminadas",
  "Everything you've delivered, grouped by month or by client.": "Todo lo que has entregado, agrupado por mes o por cliente.",
  "By month": "Por mes",
  "By client": "Por cliente",
  to: "a",
  Clear: "Quitar",
  "{n} finished · {amount}": "{n} terminadas · {amount}",
  "Nothing finished yet": "Aún no hay nada terminado",
  "Commissions land here when they reach their last stage.": "Las comisiones llegan aquí al alcanzar su última etapa.",
  "Try another search or date range.": "Prueba otra búsqueda o rango de fechas.",
  "View image": "Ver imagen",

  // Tags
  "Label library": "Biblioteca de etiquetas",
  "Classify commissions by type, payment or anything you need.": "Clasifica las comisiones por tipo, pago o lo que necesites.",
  "+ New category": "+ Nueva categoría",
  "Category name, e.g. Extras": "Nombre de la categoría, p. ej. Extras",
  Create: "Crear",
  "Start your first category": "Empieza tu primera categoría",
  "Group tags like commission types, extras or payment status.": "Agrupa etiquetas como tipos de comisión, extras o estado de pago.",
  "New category": "Nueva categoría",
  "+ Add tag": "+ Añadir etiqueta",
  "Tag name": "Nombre de la etiqueta",
  "Custom colour": "Color personalizado",
  "Not used": "Sin usar",
  "Delete tag": "Borrar etiqueta",
  "It will be removed from {usage}. This can't be undone.": "Se quitará de {usage}. No se puede deshacer.",
  "This can't be undone.": "No se puede deshacer.",
  "Could not create tag.": "No se pudo crear la etiqueta.",
  "Could not save tag.": "No se pudo guardar la etiqueta.",
  "Tag deleted.": "Etiqueta borrada.",
  "Could not delete tag.": "No se pudo borrar la etiqueta.",

  // Templates
  "Workflow library": "Biblioteca de flujos",
  "Reusable workflows: the stages a commission goes through.": "Flujos reutilizables: las etapas por las que pasa una comisión.",
  "+ New template": "+ Nueva plantilla",
  "No templates yet": "Aún no hay plantillas",
  "Create your first template": "Crea tu primera plantilla",
  "A template is the list of stages a commission moves through.": "Una plantilla es la lista de etapas por las que avanza una comisión.",
  "New template": "Nueva plantilla",
  "Template name": "Nombre de la plantilla",
  "Base price": "Precio base",
  "Revisions included": "Revisiones incluidas",
  "Add a stage and press Enter": "Añade una etapa y pulsa Enter",
  "The last stage marks the commission as finished.": "La última etapa marca la comisión como terminada.",
  "Drag to reorder": "Arrastra para reordenar",
  "Remove stage": "Quitar etapa",
  "{n} stage": "{n} etapa",
  "{n} stages": "{n} etapas",
  "{n} in use": "{n} en uso",
  "Delete template": "Borrar plantilla",
  "Its stages are deleted too. This can't be undone.": "Sus etapas también se borran. No se puede deshacer.",
  "Action not allowed": "Acción no permitida",
  "Can't delete template": "No se puede borrar la plantilla",
  Understood: "Entendido",
  "Template saved.": "Plantilla guardada.",
  "Save error: {error}": "Error al guardar: {error}",
  "Untitled template": "Plantilla sin título",
  "Template error: {error}": "Error de plantilla: {error}",
  "Duplicate error: {error}": "Error al duplicar: {error}",
  "Could not delete template.": "No se pudo borrar la plantilla.",

  // Validation errors
  "Template name is required": "El nombre de la plantilla es obligatorio",
  "Commission title is required": "El título de la comisión es obligatorio",
  "Tag name is required": "El nombre de la etiqueta es obligatorio",
  "Client name is required": "El nombre del cliente es obligatorio",
  "Character name is required": "El nombre del personaje es obligatorio",
  "Write what the client asked to change": "Escribe lo que pidió cambiar el cliente",
  "The request needs a name": "La solicitud necesita un nombre",
  "This template is used by one or more commissions (active or finished), so it can't be deleted. Duplicate it if you want a variation.": "Esta plantilla la usan una o más comisiones (activas o terminadas), así que no se puede borrar. Duplícala si quieres una variación.",
  "\"{name}\" is in use by a commission (current stage, images or corrections), so it can't be removed.": "\"{name}\" la usa una comisión (etapa actual, imágenes o correcciones), así que no se puede quitar.",

  // Search and shortcuts
  "Keyboard shortcuts": "Atajos de teclado",
  "Search and actions": "Buscador y acciones",
  "Go to a screen (menu order)": "Ir a una pantalla (orden del menú)",
  "New commission": "Nueva comisión",
  "Toggle private mode": "Activar o quitar el modo privado",
  "Show this list": "Mostrar esta lista",
  Close: "Cerrar",
  "Search commissions, clients, screens and actions…": "Busca comisiones, clientes, pantallas y acciones…",
  "No results": "Sin resultados",
  "Loading…": "Cargando…",
  "↑ ↓ to move": "↑ ↓ para moverte",
  "Enter to open": "Enter para abrir",
  "Esc to close": "Esc para cerrar",
  "Go to": "Ir a",
  Actions: "Acciones",
  "Switch language": "Cambiar de idioma",
  "Switch to light theme": "Cambiar al tema claro",
  "Switch to dark theme": "Cambiar al tema oscuro",

  // Filters shared by several screens
  All: "Todas",
  Unpaid: "Sin pagar",
  Partial: "Parcial",
  Paid: "Pagado",
};
