export const es: Record<string, string> = {
  // Sidebar
  Dashboard: "Panel",
  Commissions: "Comisiones",
  Requests: "Solicitudes",
  Clients: "Clientes",
  Tags: "Etiquetas",
  Templates: "Plantillas",
  Finished: "Terminadas",
  Settings: "Ajustes",
  "Commission workspace": "Espacio de comisiones",
  "Hide client names and prices while streaming (Ctrl+Shift+P)": "Oculta nombres de clientes y precios en directo (Ctrl+Shift+P)",
  "● Private mode on": "● Modo privado activo",
  "Private mode": "Modo privado",
  "Current theme": "Tema actual",
  "A soft workspace for tracking commissions, clients and deadlines.": "Un espacio suave para seguir comisiones, clientes y entregas.",

  // Settings
  Preferences: "Preferencias",
  "Appearance, pricing, backups and storage.": "Apariencia, precios, copias y almacenamiento.",
  Appearance: "Apariencia",
  Pricing: "Precios",
  Delivery: "Entrega",
  Backups: "Copias de seguridad",
  "Import payments": "Importar pagos",
  "Export data": "Exportar datos",
  Storage: "Almacenamiento",
  Theme: "Tema",
  "Light, dark, or follow your Windows setting.": "Claro, oscuro o el de tu Windows.",
  Light: "Claro",
  Dark: "Oscuro",
  System: "Sistema",
  Language: "Idioma",
  "The app reloads when you change it.": "La app se recarga al cambiarlo.",
  "Default currency": "Divisa por defecto",
  "New commissions start with this one.": "Las comisiones nuevas empiezan con esta.",
  "Extra character": "Personaje extra",
  "Added to the base price for each character after the first. Commissions you already created keep their price.":
    "Se suma al precio base por cada personaje después del primero. Las comisiones que ya creaste mantienen su precio.",
  "Payment platforms": "Plataformas de pago",
  'Their fees, so "received" fills itself when you log a payment. Use your real rates.':
    'Sus tarifas, para que "recibido" se rellene solo al apuntar un pago. Usa tus tarifas reales.',
  "+ Add platform": "+ Añadir plataforma",
  "Remove platform": "Quitar plataforma",
  "Promised delivery time": "Plazo de entrega prometido",
  "The longest you tell clients it can take. A commission without a deadline counts from the day you accept it.":
    "Lo máximo que dices a tus clientes que puede tardar. Una comisión sin fecha límite cuenta desde el día que la aceptas.",
  days: "días",
  "Delivery reminders": "Avisos de entrega",
  "days before": "días antes",
  "A Windows notification {days} days before and on the day, while ZeeBoard is open.":
    "Una notificación de Windows {days} días antes y el mismo día, mientras ZeeBoard esté abierto.",
  Off: "No",
  On: "Sí",
  "Stalled commissions": "Comisiones paradas",
  "Warns you when a commission has had no new image, correction, payment or stage change for a while.":
    "Te avisa cuando una comisión lleva un tiempo sin imagen nueva, corrección, pago ni cambio de etapa.",
  "Back up your data": "Copia tus datos",
  "Database and images, to any folder. Restoring saves a copy of your current data first.":
    "Base de datos e imágenes, a cualquier carpeta. Al restaurar se guarda antes una copia de tus datos actuales.",
  Export: "Exportar",
  "Exporting…": "Exportando…",
  "Restore…": "Restaurar…",
  "Restoring…": "Restaurando…",
  "Automatic backups": "Copias automáticas",
  "A copy the first time you open ZeeBoard each day. Older copies are removed automatically.":
    "Una copia la primera vez que abres ZeeBoard cada día. Las más antiguas se borran solas.",
  Folder: "Carpeta",
  "Change…": "Cambiar…",
  "Keep the last": "Conservar las últimas",
  copies: "copias",
  "Last backup: {date}": "Última copia: {date}",
  "No automatic backup yet": "Aún no hay copia automática",
  "Back up now": "Copiar ahora",
  "Backing up…": "Copiando…",
  "Choose a folder for automatic backups": "Elige una carpeta para las copias automáticas",
  "Backup saved to: {path}": "Copia guardada en: {path}",
  "Could not back up: {error}": "No se pudo copiar: {error}",
  "Could not create backup. Please try again.": "No se pudo crear la copia. Inténtalo de nuevo.",
  "Could not restore: {error}": "No se pudo restaurar: {error}",
  "PayPal activity (CSV)": "Actividad de PayPal (CSV)",
  "Matches each payment with a client by their email and adds it to their commission, with what you actually received. Payments already imported are skipped.":
    "Cruza cada pago con un cliente por su email y lo añade a su comisión, con lo que realmente recibiste. Los pagos ya importados se saltan.",
  "Last imported payment: {last}. Download from {from}.": "Último pago importado: {last}. Descarga desde {from}.",
  "Nothing imported yet.": "Aún no has importado nada.",
  "Choose CSV": "Elegir CSV",
  "One row per commission: client, type, stage, price and what has been paid.":
    "Una fila por comisión: cliente, tipo, etapa, precio y lo pagado.",
  "One row per payment: date, what the client paid, what you received and the platform fee.":
    "Una fila por pago: fecha, lo que pagó el cliente, lo que recibiste y la tarifa de la plataforma.",
  "Quarterly summary": "Resumen trimestral",
  "Payments grouped by quarter and currency, by the day you received them. Currencies are never added together.":
    "Pagos agrupados por trimestre y divisa, según el día que los recibiste. Las divisas nunca se suman entre sí.",
  Payments: "Pagos",
  "Export CSV": "Exportar CSV",
  "Opens in Excel and Google Sheets (semicolon-separated, decimal comma). Exports always contain the real names and prices, even in private mode.":
    "Se abre en Excel y Google Sheets (separado por punto y coma, coma decimal). Las exportaciones siempre llevan los nombres y precios reales, incluso en modo privado.",
  "Saved to: {path}": "Guardado en: {path}",
  "Could not export: {error}": "No se pudo exportar: {error}",
  "{size} used": "{size} usados",
  "Images {images} ({used} in use · {count} files) · Thumbnails {thumbs} · Database {database}":
    "Imágenes {images} ({used} en uso · {count} archivos) · Miniaturas {thumbs} · Base de datos {database}",
  "Open folder": "Abrir carpeta",
  "Unused images": "Imágenes sin usar",
  "Files that no commission or character uses anymore.": "Archivos que ninguna comisión ni personaje usa ya.",
  "Clean up": "Limpiar",
  "Cleaning up…": "Limpiando…",
  "No unused images found.": "No hay imágenes sin usar.",
  "Deleted {n} unused file · freed {size}.": "Se borró {n} archivo sin usar · liberados {size}.",
  "Deleted {n} unused files · freed {size}.": "Se borraron {n} archivos sin usar · liberados {size}.",
  "Could not back up first, so nothing was deleted: {error}": "No se pudo hacer la copia previa, así que no se borró nada: {error}",
  "Could not clean up images. Please try again.": "No se pudieron limpiar las imágenes. Inténtalo de nuevo.",

  // Settings dialogs
  "Replace your data": "Reemplazar tus datos",
  "Restore this backup?": "¿Restaurar esta copia?",
  "Your current commissions, clients and settings will be replaced by the ones in:\n{folder}\n\nA copy of your current data is saved first (in the app folder, \"before-restore\"), and no images are deleted. The app reloads when it's done.":
    "Tus comisiones, clientes y ajustes actuales se sustituirán por los de:\n{folder}\n\nAntes se guarda una copia de tus datos actuales (en la carpeta de la app, \"before-restore\") y no se borra ninguna imagen. La app se recarga al terminar.",
  "Restore backup": "Restaurar copia",
  Cancel: "Cancelar",
  "Permanent action": "Acción permanente",
  "Clean up unused images": "Limpiar imágenes sin usar",
  "This permanently deletes image files that are no longer linked to any commission or character. A full backup is saved first (in the app folder, 'before-cleanup', keeping the last 2), so you can restore from it if something was needed.":
    "Esto borra para siempre los archivos de imagen que ya no están enlazados a ninguna comisión ni personaje. Antes se guarda una copia completa (en la carpeta de la app, 'before-cleanup', conservando las 2 últimas), para que puedas restaurarla si hacía falta algo.",
  "Delete unused images": "Borrar imágenes sin usar",

  // Dashboard
  Overview: "Resumen",
  "What's on your desk today.": "Lo que hay hoy en tu mesa.",
  "In progress": "En curso",
  commissions: "comisiones",
  "Due within 7 days": "Vencen en 7 días",
  "including overdue": "incluidas las vencidas",
  "Waiting for payment": "Pendiente de cobro",
  "{n} commission": "{n} comisión",
  "{n} commissions": "{n} comisiones",
  "Received this month": "Recibido este mes",
  "{n} payments not entered yet": "{n} pagos sin apuntar lo recibido",
  "{amount} in platform fees": "{amount} en tarifas de plataforma",
  "Needs attention · {n}": "Necesita atención · {n}",
  "In progress · {n}": "En curso · {n}",
  "Nothing on the board. Time for a break.": "Nada en el tablero. Hora de un descanso.",
  "Not started": "Sin empezar",
  "No deadline": "Sin fecha límite",
  "Not paid yet · {n}": "Sin cobrar · {n}",
  "All caught up.": "Todo al día.",
  "Most used tags": "Etiquetas más usadas",
  "No tags in use yet.": "Aún no hay etiquetas en uso.",
  "Booked per month · by commission start date": "Reservado por mes · según el inicio de la comisión",
  "{n} day overdue": "{n} día de retraso",
  "{n} days overdue": "{n} días de retraso",
  "Due today": "Vence hoy",
  "{n} day left": "queda {n} día",
  "{n} days left": "quedan {n} días",
  "{n} day": "{n} día",
  "{n} days": "{n} días",

  // Reminders
  Overdue: "Vencida",
  Today: "Hoy",
  Soon: "Pronto",
  Stalled: "Parada",
  "your promised time": "tu plazo prometido",
  "its deadline": "su fecha límite",
  "{title} is {days} past {limit}": "{title} se pasó {days} de {limit}",
  "{title} reaches {limit} today": "{title} llega hoy a {limit}",
  "{title} reaches {limit} in {days}": "{title} llega a {limit} en {days}",
  "{title} hasn't changed in {days}": "{title} no ha cambiado en {days}",
  "{title} is past the sketch and still unpaid": "{title} ya pasó el boceto y sigue sin pagar",
  "{n} commissions need your attention": "{n} comisiones necesitan tu atención",

  // Commissions
  "Main workspace": "Espacio principal",
  "Organize your drawings by stages, clients, dates and tags.": "Organiza tus dibujos por etapas, clientes, fechas y etiquetas.",
  "+ New commission": "+ Nueva comisión",
  List: "Lista",
  Grid: "Cuadrícula",
  Queue: "En cola",
  "No commissions yet": "Aún no hay comisiones",
  "Create your first commission to start building your workflow.": "Crea tu primera comisión para empezar a montar tu flujo de trabajo.",
  "No matches": "Sin resultados",
  "No commissions match your current search or filters.": "Ninguna comisión coincide con tu búsqueda o filtros.",
  "No client": "Sin cliente",
  "No platform": "Sin plataforma",
  "No price": "Sin precio",
  "No date": "Sin fecha",
  "No base price": "Sin precio base",
  "No notes.": "Sin notas.",
  "No characters.": "Sin personajes.",
  "{n}d": "{n}d",
  "{n}d late": "{n}d de retraso",
  "Days since you accepted it": "Días desde que la aceptaste",
  "Pick a commission": "Elige una comisión",
  "Choose one from the list, or use ↑ ↓ to move between them.": "Elige una de la lista o usa ↑ ↓ para moverte entre ellas.",
  "Each client correction counts as one revision": "Cada corrección del cliente cuenta como una revisión",
  Revisions: "Revisiones",
  extra: "extra",
  "Copy the account to tag when you post": "Copia la cuenta a etiquetar al publicar",
  Tag: "Etiqueta",
  Edit: "Editar",
  "More actions": "Más acciones",
  Duplicate: "Duplicar",
  "Duplicating…": "Duplicando…",
  "Short text for the PayPal invoice": "Texto corto para la factura de PayPal",
  "Copy description": "Copiar descripción",
  Delete: "Borrar",
  "This commission has no template, so it has no stages. Edit it to pick one.": "Esta comisión no tiene plantilla, así que no tiene etapas. Edítala para elegir una.",
  "Open in focus mode": "Abrir en modo enfoque",
  "Previous alt": "Alternativa anterior",
  "Next alt": "Alternativa siguiente",
  "Add an alt": "Añadir una alternativa",
  "Remove this image": "Quitar esta imagen",
  "Optimizing…": "Optimizando…",
  "Drop or Ctrl+V": "Suelta o Ctrl+V",
  "Drop here": "Suelta aquí",
  "+ correction": "+ corrección",
  "{n} correction": "{n} corrección",
  "{n} corrections": "{n} correcciones",
  "Remove correction": "Quitar corrección",
  "What did the client ask to change? Enter to add": "¿Qué pidió cambiar el cliente? Enter para añadir",
  "Back to the previous stage": "Volver a la etapa anterior",
  "‹ Back": "‹ Atrás",
  "✓ Finished": "✓ Terminada",
  "Start {name}": "Empezar {name}",
  "{name} done →": "{name} hecho →",
  "Ctrl+V adds to": "Ctrl+V añade a",
  Notes: "Notas",
  Characters: "Personajes",
  Alt: "Alternativa",
  Alts: "Alternativas",
  Progress: "Progreso",
  Calendar: "Calendario",
  "Next deadline": "Próxima fecha límite",
  Mon: "Lun",
  Tue: "Mar",
  Wed: "Mié",
  Thu: "Jue",
  Fri: "Vie",
  Sat: "Sáb",
  Sun: "Dom",
  "Deadline summary": "Resumen de plazos",
  Deadline: "Fecha límite",
  "Deadline · optional": "Fecha límite · opcional",
  "Commission title": "Título de la comisión",
  Client: "Cliente",
  "Search or type a name": "Busca o escribe un nombre",
  "+ from another client": "+ de otro cliente",
  "· can't change after creating (stages and images depend on it)": "· no se puede cambiar tras crearla (las etapas y las imágenes dependen de ella)",
  Summary: "Resumen",
  Price: "Precio",
  "Calculated from the type and characters; you can change it": "Calculado según el tipo y los personajes; puedes cambiarlo",
  "Background, pose, details to remember…": "Fondo, pose, detalles que recordar…",
  "Saving…": "Guardando…",
  "Create commission": "Crear comisión",
  "Save changes": "Guardar cambios",
  "Delete commission": "Borrar comisión",
  "This action cannot be undone.": "Esta acción no se puede deshacer.",
  "Deleting...": "Borrando...",
  "Commission saved.": "Comisión guardada.",
  "Commission created.": "Comisión creada.",
  "Commission duplicated.": "Comisión duplicada.",
  "Could not duplicate commission.": "No se pudo duplicar la comisión.",
  "Commission deleted.": "Comisión borrada.",
  "Could not delete commission.": "No se pudo borrar la comisión.",
  "Commission error: {error}": "Error en la comisión: {error}",
  "Could not add image: {error}": "No se pudo añadir la imagen: {error}",
  "Tag copied.": "Etiqueta copiada.",
  "Description copied.": "Descripción copiada.",
  "Could not copy it.": "No se pudo copiar.",

  // Filters
  "Search title or client…": "Buscar por título o cliente…",
  "Clear filters": "Quitar filtros",
  "Remove filter": "Quitar filtro",
  Active: "Activas",

  // Payments strip
  "Client paid": "Pagó el cliente",
  Received: "Recibido",
  Date: "Fecha",
  "You received": "Recibiste",
  "Not yet": "Aún no",
  Later: "Luego",
  "Remove payment": "Quitar pago",
  "Add payment": "Añadir pago",
  "Note: PayPal, deposit…": "Nota: PayPal, adelanto…",
  "Payment error: {error}": "Error de pago: {error}",
  "Enter what the client paid": "Escribe lo que pagó el cliente",

  // Filters shared by several screens
  All: "Todas",
  Unpaid: "Sin pagar",
  Partial: "Parcial",
  Paid: "Pagado",
};
